[programs.localnet]
mymoneydapp = "E2N6zLqZ6WiiAMioPtW15RNhTGGVBxKgtYqqrZfsNmrB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/metalgear/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
